name: Log File Upload to GitHub Repository

on:
  push:
    branches:
      - main
    paths:
      - 'WorkSpace/**'  # Watches for changes in the WorkSpace folder

jobs:
  log_upload:
    runs-on: self-hosted

    steps:
    # Step 1: Checkout the repository to access the files
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Git configuration
    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    # Step 3: Append a log entry to the Log_upload file
    - name: Append log entry to Log_upload file
      run: |
        # Get the current date and time
        timestamp=$(date +"%Y-%m-%d %H:%M:%S")
        
        # Write the log message into the Log_upload file
        echo "$timestamp - A new file was uploaded to the WorkSpace folder." >> Log_upload.txt

    # Step 4: Commit and push changes to the repository
    - name: Commit and push changes
      run: |
        git add Log_upload.txt
        git commit -m "Log file upload event: $(date)"
        git push
