name: Git Push Monitor

# Trigger the workflow on a push event
on:
  push:
    branches:
      - master  # You can specify any branch or multiple branches
    #

jobs:
  monitor_push:
    runs-on: self-hosted  # Choose the operating system for the runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the push information
        run: |
          echo "Push event details:"
          echo "Pushed by: $GITHUB_ACTOR"
          echo "Branch: $GITHUB_REF"
          echo "Commit message: $GITHUB_HEAD_REF"
          echo "Commit SHA: $GITHUB_SHA"
          
      - name: Send notification (optional)
        run: |
          echo "A push has occurred in the repository. Commit: $GITHUB_SHA"
          
          # For example, you could send an email or a Slack notification here
          # Replace this with actual commands if you want to send real notifications

      # You can add additional steps to process the push further if needed
